name: Deploy website

on:
  workflow_call:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    name: GitHub Pages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: github-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
